### ISSUE TITLE
Right clicking anywhere (even on links / text area etc.) makes the default cursor replace the pointer / text cursor

### ISSUE THREAD

**Issue by FatOrangutan** [cpriest/SnapLinksPlus#115]
FF 49.0.1, Snap Links 3.0.0.2

Expected behaviour (recorded with the add-on disabled):

![wgif](https://cloud.githubusercontent.com/assets/8336638/19363774/4fb9ded6-91a9-11e6-8642-9248dd242b57.gif)

Observed behaviour (recorded with the add-on enabled):

![bug](https://cloud.githubusercontent.com/assets/8336638/19369374/9a6a56ea-91c2-11e6-844a-219c56d68156.gif)

Notice that immediately after right clicking, the pointer cursor and the text cursor are replaced by the default cursor for a moment, before reverting to their original cursor state.

Here it is slowed down:
![ezgif-1807021388](https://cloud.githubusercontent.com/assets/8336638/19369517/95fffcda-91c3-11e6-8432-cce5e05768cc.gif)

**Comment by Hrxn** [comment]
It took me almost five minutes to see what you mean....

**Comment by FatOrangutan** [comment]
Sorry for the confusion; the second gif actually includes the first gif as well which is probably why you didn't notice it at first glance. I will update it with a better capture in just about a moment..

**Comment by cpriest** [comment]
Indeed, thank you for the report.  I am going to have to get a hold of Mozilla about this one I think.  The onmousedown is being stopped/not propagated in order to prevent other event handlers from doing something on its occurrence.  If the drag area is large enough when the mouseup event fires, then it prevents the next 'contextmenu' event from occurring.  

Unfortunately it appears that some functionality is dependent on the mousedown event which I cannot have re-created, or 'paused.'

There seemed to be some hard to diagnose issues similar to this with v2 that were never satisfactorily solved either.

I would really like to get the next version released so I'm not going to let this stop the release but I will try to find some way to solve the problem.

**Comment by FatOrangutan** [comment]
That's OK, it is barely noticeable anyways.

BTW, would you have a time frame on when the next version could be available? Thanks!

**Comment by cpriest** [comment]
I had wanted to have it out by yesterday, but am building out a "welcome page" and "update page" to address the new users having no idea how to use it, etc.  I'd like to say by beginning of next week but can't say for certain.

**Comment by remi-garcia** [comment]
I can't reproduce it with Firefox 69.0 and last SL3.
Is that still an issue?
