### ISSUE TITLE
Missing "options" in FF45 on Linux

### ISSUE THREAD

**Issue by Boshomi** [cpriest/SnapLinksPlus#119]
at FF45 on Linux I can't find the options/preferences-button

**Comment by Hrxn** [comment]
v3?

Then it's expected, I'd say..

**Comment by rayman89** [comment]
Yeah on v3 he took the options out supposedly to quickly make it usable but it's been like 4 months since that release IDK why it's still not fixed. I've been using multi links plus which is very simmilar because without the options the ability to just copy multiple links has been lost and that's what I was using the add-on for.

**Comment by Hrxn** [comment]
What happens if you hold `Ctrl` during the whole link selection process?

**Comment by Boshomi** [comment]
the links get selected for Copy&Paste but no rectangle for selecting the
links to open them with tabs. now i have ff49.0.2 on linux.

hth
Gerald

2016-11-04 9:11 GMT+01:00 H R X N <notifications@github.com>:

**Comment by cpriest** [comment]
The new 3.1 version is due to be released soon, you can try the beta version by downloading https://github.com/cpriest/SnapLinksPlus/raw/master/dist/SnapLinks-3.1.0b1.xpi. 

You'll need to go to about:debug and click "Load Temporary Extension" to use this unsigned version.

Note, there is also a welcome page with instructions on use of 3.1 available here:
http://cpriest.github.io/SnapLinksPlus/welcome.html

**Comment by cpriest** [comment]
Sorry, just not enough time in the day.  Most of the features have been 
written (sans the configurability panel), I'm about 1% away from the 
next release but just swamped.

Feel free though, if you're able, to submit pull requests to contribute 
to the project.

**Comment by Hrxn** [comment]
Don't worry, take your time.. 😃
