### ISSUE TITLE
SnapLinksPlus 3.1.0.4 now working in firefox 45.5.0

### ISSUE THREAD

**Issue by catdel** [cpriest/SnapLinksPlus#127]
Good Afternoon

I have uninstalled and reinstalled Snap Links Plus in Firefox 45.5.0, I currently have Snap Links Plus version 3.1.0.4 but this does not appear to be working, when I right click the box is not fully displayed in bold dots as it used to be and the tabs dont open when I release

Kind Regards
Cathal

**Comment by holswort** [comment]
I am having the same issue. Firefox 45.5.0. I uninstalled and reinstalled, restarted firefox, etc. The rectangle doesn't register any links, and it also sticks on the screen and doesn't disappear when i let go or click. Screenshot attached.
![snap links not working screen grab](https://cloud.githubusercontent.com/assets/23529990/20400962/c1a2f8d0-acab-11e6-8815-609056c6e5d1.JPG)

**Comment by holswort** [comment]
@catdel I updated Firefox to 50.0 and it corrected the problem.

**Comment by cpriest** [comment]
There has also been a report of it not working on addons.mozilla.org (of 
all places) which is due to Content Security Policy which I do not have 
a workaround/fix (if its even possible) for yet.

@catdel: if updating to the latest FF doesn't fix it, please post a link 
to the URL (screenshot as well if possible) showing the problem so I can 
look into it.

**Comment by cpriest** [comment]
Please re-open if the latest FF is still showing a problem and include the URL where the problem is occurring.

**Comment by catdel** [comment]
Thanks for the help @cpriest and @holswort, I have upgraded to 50 and it works now
