### ISSUE TITLE
Buggy with these imgur links

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#131]
Steps to reproduce:

1. Go to https://thirteenag.github.io/wfp
2. Click on any of the blue "Screenshots" to open a gallery
3. Try to select all imgur links on the page at once with SLP

It usually ends up selecting only one image or none at all, or the rectangle needs to be positioned very carefully to select all images at once.

**Comment by cpriest** [comment]
Yeah, I can see what's going on.  Looking for a solution, the only way I can find may be computationally intensive.  I believe v2 made this calculation though for this very reason (overlays which are really visually hiding elements underneath them).

**Comment by cpriest** [comment]
This has been fixed by the latest commit and so should be available in the next minor release.  If you want the fix sooner, watch for a signed beta build soon.  I'll try to remember to post it here, but otherwise it will be located here: https://github.com/cpriest/SnapLinksPlus/tree/master/dist  (Most likely named 3.1.1b1)

**Comment by Keith94** [comment]
Alright sounds good. Would it be better to add new pre-release versions to the "releases" page instead? that's mainly what it's used for and I would receive a notification for it too. ;)

**Comment by cpriest** [comment]
Probably would be, but I don't see how to do that.  When I get it to the 
next beta point, perhaps this morning, I will look into how to do that.
