### ISSUE TITLE
current version cannot detect more links when scrolling further

### ISSUE THREAD

**Issue by thaliel** [cpriest/SnapLinksPlus#156]
at least not in seperate, srollable areas such as on this page:
http://eggcave.com/profile/thaliel

as you can see, there are way more than 20 lnks in the scrollable section. but Once I scroll further (I do not mind it not scrolling along automatically), the selection boy does not detect the further links and claims there are 0 links, which of course is not the case

**Comment by cpriest** [comment]
There's a lot going on with this page.  

1. If I select from the upper left of the page to the bottom right while holding alt, I get 50 links, so that's working.
2. None of the image links within the scrollable feed are being selected, this is odd.
3. The page does scroll along automatically (the scrollable section with 'creatures' does not, this is expected).

So from what you reported, \#1 and \#3 are fine, but \#2 is an issue.

Does that sum it up properly?

**Comment by thaliel** [comment]
I can select the first 2 creatures in the feed when limiting the selection to only the feed area. I just cannot select any more. With version 2 , I would just select 20, scroll down, select the next 20, scroll down etc. but scrolling the feed will result in current version to somehow think there are no links present within the feed area

**Comment by cpriest** [comment]
Hmm, yeah I see this is acting a bit differently than I thought.  
Knowing the code I can see why it would be reacting this way.  v2 had 
the ability to see through iFrames which took some trickery that 
possibly also took care of this edge case.  I'll look and see how I did 
that in v2 and may try to implement that feature in v3 at some point.

**Comment by bluebellrose** [comment]
It seems to be an issue with Hydra. Something in the hydra javascript is blocking it. it runs fine on yarolds. I would advise talking to vandall asking what is he doing blocking the use of snaplinks

**Comment by remi-garcia** [comment]
If I understood this issue well it works now and that can be closed

**Comment by cpriest** [comment]
@thaliel is this still an issue?
