### ISSUE TITLE
adding extra links

### ISSUE THREAD

**Issue by thaliel** [cpriest/SnapLinksPlus#171]
when on my profile on https://eggcave.com , the selection will sometimes believe there are more links than there actually are.
you can see here
http://i364.photobucket.com/albums/oo86/Thaliel/eggcave_zpsvwyqj111.png
that although there should only be 12 links, it says 13, the 13th being a completely unrelated site that is being opened additonally to the 12 links selected

**Comment by cpriest** [comment]
There must be a link hidden there somewhere that's being grabbed.  Is there any way for me to get to the page that's causing it?

**Comment by thaliel** [comment]
Unfortunately not. I switched to othr extensions with the same functionality, and it also happens. Multi LInks gave me the opportunity to see an extra area within the selection that shouldn't be there (because why should a site link to a completely different one they do not even know about?). For some reason, snaplinks plus aa well as its competition extensions are made beleive there is an extra link, even though there is not, and they believe that link is one of my other bookmarks.

**Comment by cpriest** [comment]
@thaliel See if the latest beta still has the issue or not.

If so... Can you save the web page ('complete') and zip the files up and upload them here?  Would that be possible without compromising your private/secure data?  

Alternatively, to uploading it to GitHub (public), you could email it to me directly if you feel safe in doing that.

If there is some way for me to test it I can take a look, otherwise I can't.

**Comment by thaliel** [comment]
forgot this was still open. It has been resolved
