### ISSUE TITLE
Add support for container tabs

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#178]
Wiki page: https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

Would be nice having the ability to lasso and open multiple links in a specific container.

**Comment by DilectableBananaButterfly** [comment]
Links open in the Default container rather than the container the page is in. This posts significant issues for the user as cookies and other data are relative to the container/context they are opened in. Among other issues related to user security and configuration, containers allow a user to have multiple credentials for the same site active at once (e.g., work , personal , etc ).  If a link from the "personal" container is opened in the Default container, Snap Links can potentially open the link _under the wrong credentials_.

**Comment by cpriest** [comment]
Ouch, that's a big problem, will be sure to prioritize this as soon as I can get back to this project.

**Comment by bunnybooboo** [comment]
This missed the roadmap?

**Comment by cpriest** [comment]
Nope, it's all fixed, just hasn't been released yet.

**Comment by bunnybooboo** [comment]
Ya superstar!!! It'll be especially useful in code reviews. Thanks for taking the time to respond.

**Comment by cpriest** [comment]
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
