### ISSUE TITLE
Not working with Service Now

### ISSUE THREAD

**Issue by philipdoan** [cpriest/SnapLinksPlus#187]
Hi Clint!

This extension is not working on ServiceNow. The rectangle does not even show up when right clicking.

**Comment by cpriest** [comment]
Does the error console show anything on that website to do with CSR 
violations?

**Comment by philipdoan** [comment]
How do I reach the error console?

**Comment by philipdoan** [comment]
Hey Clint!,

Does this work?

The error console says:

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://location.services.mozilla.com/v1/country?key=fa6d7fc9-e091-4be1-b6c1-5ada5815ae9d. (Reason: missing token ‘x-csrftoken’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel)."

**Comment by philipdoan** [comment]
It also says:

Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://addons-amo.cdn.mozilla.net 'sha256-DiZjxuHvKi7pvUQCxCVyk1kAFJEUWe+jf6HWMI5agj4='”).

**Comment by cpriest** [comment]
Yes, To My Knowlege there is no way for me to get around this.  Either this has to be fixed by Mozilla, or it's the expected behavior.  CORS is a security mechanism, that website is basically saying from where other resources may be loaded.  If you find out anything to the contrary, let me know but I believe that is the situation.
