### ISSUE TITLE
Add Choice to Open new Tabs at End of Bar

### ISSUE THREAD

**Issue by NightDrag0n** [cpriest/SnapLinksPlus#193]
Hi,
I would love it to have a option to choose if i want to open my links in new tabs right behind my current Window (as it does it right now even with FF set to open new tabs at end) or to have them been opened at the end of the tab bar like the older (2.4.3 Version) does wich i still use at the Moment.

**Comment by btanner2** [comment]
+1

**Comment by btanner2** [comment]
Hi, well I waited a long time for this improvement and I would like to ask very politely, if it is possible to have that options in the near future?  A checkbox “open new tabs always at the end of tab bar” in settings would be great. Is there any chance for this?

Kind regards
Brian

**Comment by cpriest** [comment]
There is but I have numerous projects I work on in my limited free 
time.  Feel free to submit a PR if you'd like to help make it happen sooner.

**Comment by btanner2** [comment]
Her you go:

https://github.com/cpriest/SnapLinksPlus/pull/252

:)

Kind regards
Brian

**Comment by btanner2** [comment]
@cpriest: thanks for merging. Would it be possible to release an official mini update with this new check box? Unfortunately I can't install an unsigned add-on in the normal Firefox Version (only in Developer Version). That's why I would appreciate it very much, if you would roll out an updated version.
Is that possible?
Thx Brian

**Comment by cpriest** [comment]
Yeah, I'll try and get that pushed out in the next couple of days.
