### ISSUE TITLE
Activation Key

### ISSUE THREAD

**Issue by coinoper8edboy** [cpriest/SnapLinksPlus#236]
Thank you for giving us the ability to select which key activates the lasso. 

On version 2.4.3 when selecting the middle mutton I was able to use the side buttons on the mouse to do the selection. But in the new version it does not work. The side button can close tabs just like it has always been, so the mouse functions as normal.

In Windows and Linux I use the right button, but on a Mac it's very annoying since the right clicking produces a menu. So if the side button can activate it like it used to be, it would be very useful.

I just noticed it, by selecting the middle button middle clicking a link does not open the link. ( It should open the link in the background )

Another thing is to get the tabs to open at the end rather than after parent tab.

Thank you in advance.

**Comment by cpriest** [comment]
Wow, a lot of things in here, sorry I haven't been able to respond to the ticket.

It sounds like you are trying to use a mouse button other than left/middle/right, is that right?  I believe I could easily add **menu options for "button 4" and "button 5"** which is usually what those come through in the event as.

Middle-clicking was reported elsewhere and should be fixed in v3.1.6 release.

The feature to open at the end was already requested and is already released.

**Comment by coinoper8edboy** [comment]
That would be great. Hope to see it soon.

Thank you very much.
