### ISSUE TITLE
Links do not open

### ISSUE THREAD

**Issue by Lehoia** [cpriest/SnapLinksPlus#261]
Hi, I am using SnapLinksPlus for a really long time already, but since I 'cleaned' mij Firefox (Removing cookies, data etc.) my add-on isn't working anymore.
I can not open multiple links, so I am using Google Chrome now, but I like Firefox much more.

Maybe it's  a known bug, or something which is unknown.

These are the things I tried:
1. reinstalling the add-on.
2. shutting down my pc.
3. reinstalling firefox.
4. cleaning firefox.
5. having a lot of patience.

I hope someone can help me out.

Lehoia.

**Comment by cpriest** [comment]
Unfortunately Mozilla decided on a new policy regarding libraries being 
used and a reviewer has disabled all releases since 2016 which means you 
probably have an old version installed now which doesn't work with the 
newer versions of Firefox.

I'll Close#261 this ticket, if you have version 3.1.0.4 installed, this 
is what the case is.

If that's not right, please re-open this ticket.

-Clint

**Comment by cpriest** [comment]
I just published 3.1.5, assuming it's not rejected it should be back to good.
