### ISSUE TITLE
stopped working completely on firefox Version 63.0.3 (32-bit) 

### ISSUE THREAD

**Issue by kestralkitsune** [cpriest/SnapLinksPlus#262]
thought that something might have bugged, so I completely uninstalled refreshed browser and then reinstalled snap links plus, but it does not simply work anymore. I right click and it will show the selection box but does not select anything or open in new tabs.

**Comment by nancylnichols** [comment]
@kestralkitsune I'm having the same problem. I bought a new desktop, now Snaplinks isn't working on new computer.

**Comment by mad-tunes** [comment]
I think I'm seeing the same.
Dragging over links with the right mouse button shows the green selection rectangle and count of links, but when I let go of the right mouse button nothing happens but the selection box and count disappearing.
This is on a new updated install of Windows 7 (x64 6.1.7601), using Snap Links 3.1.1.3 on Firefox 63.0.3.
Is there any more info that might be of use?

**Comment by nancylnichols** [comment]
Snaplinks is still working on my old laptop & using Chrome, but I prefer Foxfire & my new computer. I moderate on a site & Snaplinks really speeds up my work there.

**Comment by mad-tunes** [comment]
Just checked one of my other machines.. Server 2008R2, Snaplinks 3.1.4 and FF 63.0.3 - and snaplinks is working perfectly on there.

..why would the new win7 install have an older version of snaplinks than the old 2008R2, and how could I get it updated?

**Comment by mad-tunes** [comment]
I made the mistake of reinstalling snaplinks on the 2008R2 machine (hoping it might reinstall OK and that get synced to the win7 machine).. its installed 3.1.1.3 and now doesn't work on either machine.

Wondering if there's a file I could use to install a current version manually?

Found this page: https://gitter.im/SnapLinks/Lobby
(but I'm not signing up to comment there too)
Looks like the author might have already seen versions rolling back..

Edit: I've just got both working
On Server 2008R2 machine:
Closed FF and had a poke around in my FF profile folder (find it by going to Help>Troubleshooting info)
Stumbled accross \extensions\snaplinks@snaplinks.mozdev.org.xpi
Restored a copy of that file from a backup taken this morning
Opened FF.. it reported V3.2.4 but I didnt get the selection rectangle
Closed and re-opened FF - and snaplinks is perfect again

Copied the same restored file to the win7 machine and opened/closed/opened FF and that one started working too.
My best guess is a wrong/old version that doesn't play nice with FF 63.x could be being pushed out?
(..and my long-time working 2008R2 machine hadnt 'updated' to the old version on its own because its version number was higher, only breaking when I forced it to?)

Had a hunt around and found https://github.com/cpriest/SnapLinksPlus/tree/master/dist , but its only got versions older than the one that didnt work for me.

I've .ZIPped and attached the version of the file that works for me in case its of use.
(I recommend keeping a copy of your original so you can put it back if you want.)
[snaplinks@snaplinks.mozdev.org.zip](https://github.com/cpriest/SnapLinksPlus/files/2654077/snaplinks.snaplinks.mozdev.org.zip)

**Comment by mad-tunes** [comment]
The text for snaplinks in about:addons already includes this:

> Important: Mozilla has currently disabled the latest few version releases back to 2016 (v3.1.1.3) which does not work in the current browser.
> I am working on the issue and hope to have an updated release that they will approve ASAP. This is not a security concern, but a Mozilla policy change.

I had read but somehow didn't understand it before I found this issue/thread. 

@cpriest, I do hope you don't mind me posting your file?
(if you think its a good idea and that the approach is OK for now, you could maybe post a more official copy for anyone who wants to do the same? It might be a horrid idea though, I've no idea how FF add-ons work and just guessed)

**Comment by penyos** [comment]
It just suddenly stop working somehow, and mine is 63.0.3 (64-bit).
Please fix it the issue asap, thanks.

**Comment by cpriest** [comment]
Apologies for the lack of communication, this is due to a new policy at Mozilla that I was already working towards resolving.  Had to do with a library I'm using that the reviewer "Couldn't build" and so they deactivated all of the more recent versions of SnapLinks.

I'm hoping to have this fixed within the next few days if time allows.

**Comment by cpriest** [comment]
If anyone has some time to submit a PR explaining it for the README, I'd appreciate it!

**Comment by cpriest** [comment]
I just published 3.1.5, assuming it's not rejected it should be back to good.

**Comment by penyos** [comment]
Yes, it's working fine now.Thanks so much.

    On Monday, December 10, 2018, 6:52:45 AM PST, Clint Priest <notifications@github.com> wrote:  
 
 
I just published 3.1.5, assuming it's not rejected it should be back to good.

**Comment by mad-tunes** [comment]
3.1.25 is working a treat for me too, both after a normal update to it and if I remove and install it from scratch.
Thanks a ton for all the the effort that goes into this. I use SnapLinksPlus all the time, it saves me tons of clicks

**Comment by cpriest** [comment]
You're welcome, my pleasure.

**Comment by kestralkitsune** [comment]
sweet. it works just fine now!
