### ISSUE TITLE
Support for TreeStyleTab

### ISSUE THREAD

**Issue by rsalmei** [cpriest/SnapLinksPlus#315]
Hello man,
I like this addon very much. Still waiting for #313 to make it great.
There's just a small thing I just noticed, the tabs opened by this do not correctly nest below the parent tab in TreeStyleTab... They open as "independent tabs". Would it be possible to fix that?

**Comment by remi-garcia** [comment]
Hi,
In order to open tabs we use `browser.tabs.create()` (see [the code](https://github.com/cpriest/SnapLinksPlus/blob/35e9c0cd871379069f7142e19f6a27e481c85623/src/background-scripts/background.js#L59) and the [Mozilla API](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create).
I quickly checked on [TreeStyleTab](https://github.com/piroor/treestyletab/tree/trunk) and I'm not sure that's something we can fix on our side.

**Comment by rsalmei** [comment]
Humm, that's odd.
If I do:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/6652853/100951202-da0ad000-34ec-11eb-9d30-af826ff52ba9.png">
It correctly nests below this tab:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/6652853/100951217-e55dfb80-34ec-11eb-8a3b-1d5b1db26b11.png">

But if I do:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/6652853/100951594-9e243a80-34ed-11eb-9a42-403407cea088.png">
It opens as an independent tab:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/6652853/100951610-a8decf80-34ed-11eb-98c8-36610bf1ed91.png">

**Comment by remi-garcia** [comment]
What I suspect (but it really need a check) is that TreeStyleTab overwrite the default "Open Link in New Tab" behavior (which, by defaults, calls the same API?). Otherwise I really have no idea why it doesn't handle correctly our way to open links. I'll get a deeper look into their code today and maybe raise an issue on their side to ask for their expertise.

**Comment by remi-garcia** [comment]
That's something we probably can solve on our side. See their [API for other addons](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#open-new-child-tab-from-a-specific-tab).

In [create](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create) we can add the optional parameter **openerTabId**.
To get that ID we can use [tabs.Tab.id](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab).

I'll do some testing and add that feature.

**Comment by remi-garcia** [comment]
Actually it is already done. You have to check a box in your preferences: in Advanced Settings, `Set opening tab property for new tabs`
![Screenshot from 2020-12-03 12-54-26](https://user-images.githubusercontent.com/47191601/101015004-04996f00-3567-11eb-887f-516647369886.png)

**Comment by rsalmei** [comment]
Nice, thanks!
