### ISSUE TITLE
100+ links fail to copy sometimes

### ISSUE THREAD

**Issue by Fackym** [cpriest/SnapLinksPlus#321]
if you try to copy a large amount of links for example 100+ videos from YouTube recommended videos (in other pages too) sometimes you press ctrl to copy all selected links to the clipboard but it doesn't copy anything, this happens intermittently, is there a limitation from the browser? like the page unloading when out of screen?

**Comment by cpriest** [comment]
The ctrl key needs to be held down upon release unless it is your default action, otherwise it will do your default action.

If the page unloads or the elements are removed from the document (say because of them scrolling off canvas in a virtual backed scrolling list), those elements probably would not be copied.  It should give an indication of that though in that the number of links would not be what you'd expect.

If you can find a URL where I can reliably reproduce the issue, please add it to this ticket.
