### ISSUE TITLE
Checkboxes aren't selected in Prestashop

### ISSUE THREAD

**Issue by tjerry** [cpriest/SnapLinksPlus#334]
Hello

Selecting multiple checkboxes in the Prestashop orders list, doesn't work.

![2021-06-16_13-11](https://user-images.githubusercontent.com/2649031/122225718-99393e00-ceb5-11eb-8026-346409546864.png)

You can quickly check that yourself on https://demo.prestashop.com/#/en/front > Explore Backoffice > Log in > Order > Orders

**Comment by remi-garcia** [comment]
It is because these are not really "checkbox" but fancy javascript triggered boxes (see screenshot)

IMHO this "bug" is on the website side and solving it would require a dedicated method for that specific website. I tagged the issue "website-bug" but I think it can be closed.

![Screenshot from 2021-06-16 16-24-41](https://user-images.githubusercontent.com/47191601/122237267-7b70d680-cebf-11eb-8696-f43df8bff70c.png)

**Comment by tjerry** [comment]
Thanks for the details.
