### ISSUE TITLE
Changes to Pale Moon GUID and XUL Overlay Adjustments

### ISSUE THREAD

**Issue by mattatobin** [cpriest/SnapLinksPlus#59]
Greetings, My name is Matt A. Tobin and I am a contributing developer and Addons site Administrator for the Pale Moon project. I am writing this bug post to inform you that the Pale Moon browser (originally and historically forked from Firefox) has changed it's GUID. Though we have made modifications to allow Firefox addons to install with the Firefox GUID this change does not cover the Application XUL Overlays that allow your addon to address many Gecko based applications.

While we are preserving the Pre-Australis UI and continuing down our road of independent development this change has partly crippled your addon. The modifications to your install.rdf and chrome manifest files are minor and it would be appreciated if you would support Pale Moon out of the box as the growing number of users in the community using Pale Moon steadily increases.

More information can be found here: https://forum.palemoon.org/viewtopic.php?f=1&t=5440

If you have any additional questions please contact us either via this bug, our forums, or my self by email.

Thank you for your time and consideration!

Peace,

Matt A. Tobin

Contributing Developer / Beta Tester / 3rd Party Build Contributor / Addons Site Administrator 
The Pale Moon Project

**Comment by cpriest** [comment]
Alright, I believe the latest 2.4.2 release has the appropriate application target, could one of you Pale Moon users verify this is working properly?  I can't promise support for Pale Moon but will do what I can to keep it compatible.

**Comment by delicacy1** [comment]
nope, it doesn't, i had to modify

application={ec8030f7-c20a-464f-9b0e-13a3a9e97384}

"TO >>"

application={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}

in chrome manifest,
& i also added palemoon in the rdf

I was hoping to see the youtube links fix but still no luck in 2.4.2

**Comment by cpriest** [comment]
Apparently I grabbed the wrong guid when i did the build.
I didnt create the build system for SLP and wasnt aware the update.rdf was even being included but ill update it there as well.
Unfortunately I did not have the time to do anything more than fix the impending problem with FF35 but may have some additional time in the coming weeks to devote some more time to the project.
-Clint






 From: delicacy1 <notifications@github.com> To: cpriest/SnapLinksPlus <SnapLinksPlus@noreply.github.com> CC: Clint Priest <github-general@rxv.me> Subject: Re: [SnapLinksPlus] Changes to Pale Moon GUID and XUL Overlay Adjustments (#59) Date: 1/13/15, 10:13 AM

 nope, it doesn't, i had to modify 

 application={ec8030f7-c20a-464f-9b0e-13a3a9e97384} 

 "TO >>" 

 application={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4} 

 in chrome manifest, 
 & i also added palemoon in the rdf 

 I was hoping to see the youtube links fix but still no luck in 2.4.2

**Comment by cpriest** [comment]
I see, I didn't realize the chrome.manifest targeted the application directly.  The install.rdf file from the download off mozilla addons had the pale mode em:target id properly, are you sure you had to add it?

**Comment by Nuriell** [comment]
In the 2.4.2 the em:target for Pale Moon is present but the extension will not work, at least for me.

If i try to select links nothing happen, no selection is shown even if in the Extesions list is shown as working.

**Comment by cpriest** [comment]
Alright, I think I have the Pale Moon changes required done right, could one of you check out this b1 release?  It's otherwise identical to 2.4.2

https://github.com/cpriest/SnapLinksPlus/releases/tag/rel_v2.4.3b1

**Comment by delicacy1** [comment]
its fine

**Comment by cpriest** [comment]
Good good, thanks.

**Comment by Nuriell** [comment]
I can confirm this, work perfectly

Snap Link Plus is one of the best extensions around, its value and commodity is immense, is one of the three extensions that changed my way to use internet making my life a lot easyer (the other two are AdBlock and TabMixPlus).

As a little token of my appreciation i just donated 10$ from the Mozilla Update site.

Thanks again an keep it on. :)

**Comment by cpriest** [comment]
Thanks, much appreciated!

**Comment by delicacy1** [comment]
error.......... detected.

I don't know what you've changed in v2.4.3b1 but it's buggy now. i had to redownload
v2.4.2 & again,
modify 
application={ec8030f7-c20a-464f-9b0e-13a3a9e97384}
"TO >>"
application={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}
in chrome.manifest.

You did something that injects a bug that i found in multilinks....... the abandoned addon.
& that was reported online by 2 other users before.

When you start typing in forms it hangs & firefox windows are swapped,
the focused window is covered by another one..
it's gonna be hard for you to detect that bug because it often happens with a heavy
session with many windows & tabs & after a few minutes or half an hour of activity.
& it's not memory issues, like i tell you it's been confirmed by other users & the
bug is in multilinks & now in your latest beta.

**Comment by delicacy1** [comment]
The version i had was fine & didn't have that bug.
Just leave the rdf file untouched, palemoon doesn't force the presence of
its reference in the rdf file to be compatible as long as firefox is there.

This version works:

http://www.filedropper.com/snaplinksplus-241b3

This is what i have in chrome.manifest:

overlay chrome://browser/content/browser.xul chrome://snaplinksplus/content/overlay.xul application={ec8030f7-c20a-464f-9b0e-13a3a9e97384} application={8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}
overlay chrome://navigator/content/navigator.xul chrome://snaplinksplus/content/overlay.xul application={92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}

**Comment by cpriest** [comment]
So what you've written above doesn't jive with what @mattatobin wrote in the original post here: http://forum.palemoon.org/viewtopic.php?f=1&t=5440

Says there I need a separate overlay line as well as the additional <em:targetApplication>, can someone from PaleMoon chime in here?

**Comment by delicacy1** [comment]
I don't know, but if you're refering to that advice, mattatobin can be right but it's not a standard instruction. also, he tells "you need to remove Firefox target application block from your install.rdf"
which is something you haven't done.. if you want my advice cpriest, instead of making 5000 tests,
use my version & update it from now on.. in my version rdf is untouched & palemoon integrates it
perfectly. also, firefox application ref is untouched, only the palemoon is added & doesn't replace the firefox one. result: in my version, i don't face the hang issue with forms & window swapping like in your last beta & in multi links(latest). Just use my beta which is your previous beta including the app ref in chrome manifst (added, not replacing firefox app ref). you have much more important issues to care about, like youtube's issue.

replace your latest beta with this:
http://www.filedropper.com/snaplinksplus-241b3

cause no issues are found with palemoon with that version.
i'm not a coder but another coder gave me the fix.

thanks.

**Comment by mattatobin** [comment]
I actually don't know if you CAN chain multiple application={guid} properties to a single overlay..

But proper Mozilla code standards say you should make them separate.

**Comment by delicacy1** [comment]
it works..

**Comment by mattatobin** [comment]
It MAY work.. but it is proper.

**Comment by cpriest** [comment]
Apparently it is:

https://developer.mozilla.org/en-US/docs/Chrome_Registration




So, I can make that change, but should I include a separate application 
target as well as per your original post instructions?

**Comment by delicacy1** [comment]
Personally, i don't see the need to maintain two versions as long as you added compatibility

**Comment by mattatobin** [comment]
Yes you should add a Pale Moon 25 target application. minver 25.0 maxver 25.* with our guid.

@delicacy1 Again, please stop.

**Comment by delicacy1** [comment]
you want to muzzle me ? r u my tutor to ask another adult to stop ? RETARD ?

if there's compatibility, why do you want to make a coder waste his time & maintain two versions of his addon ? grow up mong

**Comment by drivetheory** [comment]
seeing this come to Pale Moon 25+ would be fantastic.
