### ISSUE TITLE
SnapLinksPlus not working with Google Docs

### ISSUE THREAD

**Issue by s2dent** [cpriest/SnapLinksPlus#65]
SnapLinksPlus not working with new spreadsheets in Google Docs.
For example: https://docs.google.com/spreadsheets/d/1GGDb97NA87MhO2K3EE4oDdY-sA_CgkZxa1ml99LBgH4/edit?pli=1#gid=0
Thank you in advance. Best regards.

**Comment by cpriest** [comment]
Yeah, Google is doing some funky things there.  What you see is not actually an <A> link at all.  In fact I had trouble finding the data in the DOM at all (it's not in the DOM, it's in a javascript tag as JSON data.

With the way they are handling the document, it's just way outside the scope of this project, it's a shame they can't use standard web technologies to present the data, then again it could be done this way so that a browser can support a spreadsheet.

**Comment by s2dent** [comment]
Too bad.(
Thanks so much!
