### ISSUE TITLE
Feature request: tthe option to trigger onclick events in addition to or instead of opening their href

### ISSUE THREAD

**Issue by DoomTay** [cpriest/SnapLinksPlus#87]

**Comment by cpriest** [comment]
This feature actually already exists, however it is hidden/automatic.  If you select a number of elements, the greatest number of types are what is acted upon.  For example if you lasso'd 5 <A> tags, 3 of which were href="http://..." links and two if which were href="javascript:..." then it would open the regular links, however if 3 were of the javascript: variety and 2 of the other, then it would .click() the <A> tags.

This isn't quite exactly what you're looking for, I investigated doing this one time and it was too computationally intensive to identify every element that had an onclick event registered to it.

In any case, the project is undergoing a complete rewrite because XUL based addons are being deprecated in favor of a standard browser extension.

I will close this comment but attempt to keep it in mind as I write the new version.
