### ISSUE TITLE
Doesn't work well with imgur.com's comments section

### ISSUE THREAD

**Issue by FatOrangutan** [cpriest/SnapLinksPlus#96]
Test link: [https://imgur.com/gallery/lwjG2CF](https://imgur.com/gallery/lwjG2CF)  
  
Try to select the link in the top comment.  
  
Expected result, from a similar add-on:
![screenshot 20](https://cloud.githubusercontent.com/assets/8336638/16273211/632e75ce-38be-11e6-9602-bb2c98d06f44.png)  
  
With SnapLinksPlus:  
![screenshot 19](https://cloud.githubusercontent.com/assets/8336638/16273217/715850a2-38be-11e6-9048-9156143f78b2.png)
  
Would be great if this can be fixed.

**Comment by cpriest** [comment]
This is unusual because SnapLinks has functionality built in for just 
that exact behavior in terms of text based <A> elements, it will, by 
default only highlight the largest font size link.

Looking at the website I can see that they are not all <A> references 
but are non-the-less clickable elements.  The font-size comparison 
feature does not compare between different types of clickable elements.

I will take this into account with the rewrite, currently v3 is under 
review however it lacks most features that v2 does at this point.

**Comment by Hrxn** [comment]
> Expected result, from a similar add-on:

@FatOrangutan Why didn't you name it, though?

**Comment by FatOrangutan** [comment]
> Why didn't you name it, though?
  
Linking to a similar add-on didn't seem like a good thing to do and it wasn't very relevant either, so I didn't. [Here](https://addons.mozilla.org/en-US/firefox/addon/link-ninja/) it is anyways.  
  
I switched from SnapLinksPlus to Link Ninja because of imgur, but the latter has its own issues and doesn't seem to be actively developed. I am looking to come back to SLP but I need it to support imgur first.

**Comment by cpriest** [comment]
Truth be told SLP isn't "actively" developed either, I really don't have 
the time any longer.  I am looking for some people to help contribute to 
its development, even if that means helping them to learn Javascript.

It's a ton of fun anyways, to program that is.

That being said I have made some headway with V3, sooner or later v2 
will no longer work for Firefox due to multi-process coming.

**Comment by cpriest** [comment]
So this issue is now fixed in the up coming release of v3.0.3  Been a long time, but I've just tested this scenario and it's GTG.

**Comment by cpriest** [comment]
Just because I know imgur can be 'troublesome,' I tested the latest commit against this site again and sure enough, had some problems.  I did address the issue though (and added the link from this ticket to my 'trouble links' section to test against regularly. :)

**Comment by FatOrangutan** [comment]
Thank you! I have been using v3.1.0.4 on imgur quite a lot and it works pretty well!
